### ISSUE TITLE
Provide a function to extract custom tokens from Properties

### ISSUE THREAD

**Issue by paxtonhare** [marklogic-community/ml-app-deployer#138]
Say I read in gradle.properties (or whatever). I'd like to be able to pass this Properties object to a function that would then auto create custom tokens for search/replace for me based on some prefix pattern.

So say I pass in Properties and "^ml.+" I would expect it to make custom tokens based on all of the ml.+ keys that are present in the Properties.

This keeps me from having to manually register every single replace token that I want to use.

**Comment by rjrudin** [comment]
@paxtonhare At least in ml-gradle, I think we'd need one property to specify the prefixes, and it can default to "ml". Would be a comma-delimited value. So if I'm working on an app "abc" and I have a lot of abc-specific properties prefixed with "abc", I'd have this in gradle.properties:

    mlTokenPrefixes=ml,abc

or just this in case I don't want any of the ml* properties:

    mlTokenPrefixes=abc

Sound good?

**Comment by rjrudin** [comment]
Actually, what if we just had an "mlPropertyTokenPrefix" that defaults to "@ml.", like Roxy, and then anything in gradle.properties - or some other property source - is automatically added as a token.

**Comment by paxtonhare** [comment]
@rjrudin sounds good.

**Comment by rjrudin** [comment]
This will be a primary focus for 3.1.0

**Comment by rjrudin** [comment]
Need to think about the design of this some more.

**Comment by rjrudin** [comment]
Running into the problem here as part of data-explorer work. It should be possible to feed a Properties/PropertySource object into the AppConfig and have everything registered as a custom token, perhaps with a configurable prefix/suffix.

**Comment by rjrudin** [comment]
I think ml-gradle can then have an ml-gradle-specific property that allows a user to say - "Take every property that Gradle knows about and toss it into the custom tokens map, again with an optional prefix/suffix". 

I think the custom tokens map is beneficial in that it controls what is used for replacing stuff in modules/payload files. Just need better mechanisms for populating it. 

@paxtonhare How does that sound?

**Comment by rjrudin** [comment]
@paxtonhare Your original use case can be satisfied via:

    PropertiesSource ps = new SimplePropertiesSource(props);
    appConfig.populateCustomTokens(props, "@ml.", "") // or ^ml.
