### ISSUE TITLE
Setting Replica Forest Data Path

### ISSUE THREAD

**Issue by gduplantier** [marklogic-community/ml-app-deployer#168]
How to set the replica forest data path without having an entirely customized forest configuration. I would like to use mlDatabaseNamesAndReplicaCounts and have the replica forests use the same directory as the primary forests by default. Or, use a property for the replica forest path that I can set in gradle.properties.

Issue moved from marklogic-data-hub project, [Issue 441](https://github.com/marklogic/marklogic-data-hub/issues/441)

**Comment by rjrudin** [comment]
@gduplantier By "same directory", do you mean that the replica and primary forests have the same parent directory - e.g. /var/opt/MarkLogic/Data/Forests? That's the default behavior, so it seems the scope of this ticket should be adding a property to set the "data-directory" for each of the replicas. While doing that, it'll be easy to add properties for other fields such as "large-data-directory" and "fast-data-directory". 

Also, are you looking to specify this per database, or would one directory work for all replicas created? e.g. 

mlReplicaDataDirectory=/some/path

or

mlReplicaDataDirectories=my-content,/some/path,my-triggers,/some/other/path

**Comment by gduplantier** [comment]
@rjrudin By "same directory" I was actually talking about when I set a custom data dir for the primary forests. I didn't make that clear.  However, having a property is the most configurable way to do it.  The situation we face on the SC project is that we have a single dir (not ML default) for all our forests including replicas. So, we don't need it per database.

**Comment by rjrudin** [comment]
Got it. The dev branch is currently for 3.0 work, but I'll toss this into 2.8.0.

**Comment by rjrudin** [comment]
@gduplantier How soon do you need a fix for this? Just wondering if I want to wait to add anything else to 2.8.0, otherwise I can have it ready by the end of the week, if not today.

**Comment by gduplantier** [comment]
It's not urgent.  Thanks.

**Comment by rjrudin** [comment]
Going to add mlReplicaForestDataDirectory, mlReplicaForestLargeDataDirectory, and mlReplicaForestFastDataDirectory. There are other forest fields, but those 3 seem like the most likely to need customization without resorting to full forest payloads.

**Comment by rjrudin** [comment]
@gduplantier Just realized that replicas can be created via the "forest-replica" field in a forest payload, and the only supported properties are name, host, data/fast/large. Which is good, and using this technique is more efficient than what I was doing before, which was creating each replica separately, and then associating it with the primary forest.

**Comment by rjrudin** [comment]
Will add this to ml-gradle 2.8.0

**Comment by gduplantier** [comment]
@paxtonhare How does this dependency get added to the data hub project? Will it be in next version? Does it need a ticket? I can test it on my fork if you need help.

**Comment by rjrudin** [comment]
This is now part of 2.8.0, which I just released - new properties are defined at https://github.com/marklogic-community/ml-gradle/wiki/Property-reference , starting with mlReplica. Verified this works on ml8 and ml9 too.
