### ISSUE TITLE
Support directory name for choosing content database

### ISSUE THREAD

**Issue by paxtonhare** [marklogic-community/ml-app-deployer#171]
see https://github.com/marklogic-community/marklogic-data-hub/issues/443

Right now many commands are using:
```java
String dbName = databaseIdOrName != null ? databaseIdOrName : context.getAppConfig().getContentDatabaseName();
```
@rjrudin suggested we use a subdirectory that is the name of the target database.

So instead of:
```
/temporal/axis/temporal-system-axis.json
```
We'd have:
```
/temporal/my-database/axis/temporal-system-axis.json
```

**Comment by paxtonhare** [comment]
The classes in question are:
```
DeployAlertActionsCommand
DeployAlertConfigsCommand
DeployAlertRulesCommand
DeployConfigsCommand
DeployTargetsCommand
DeployTemporalAxesCommand
DeployTemporalCollectionsCommand
DeployTemporalCollectionsLSQTCommand
DeployViewSchemasCommand
```

**Comment by rjrudin** [comment]
@paxtonhare Thoughts on:

    /alert/my-database/configs/my-config.json
    /temporal/my-database/axis/my-axis.json

vs:

    /databases/my-database/alert/configs/my-config.json
    /databases/my-database/temporal/axis/my-axis.json

The implementation doesn't really matter, I'm just wondering which seems more intuitive. I lean towards the latter; I regret adding e.g. "/alert" and "/temporal" as top-level directories, because really, they belong to a database.

**Comment by paxtonhare** [comment]
latter works for me.

**Comment by rjrudin** [comment]
So "databases" can then have directories named after specific databases, and each "my-database" directory can have alert, temporal, flexrep, and view-schemas subdirectories. ml-app-deployer will still support top-level alert/temporal/flexrep/view-schemas directories as a convenience for the common case of having a single content database and for backwards compatibility.

**Comment by rjrudin** [comment]
See https://github.com/marklogic-community/ml-app-deployer/wiki/Deploying-resources-to-databases

**Comment by rjrudin** [comment]
@paxtonhare ml-app-deployer supports this now for all 4 resource types. Will get 2.9.0 soon, looking to see what else is worth adding to that.
