### ISSUE TITLE
Is it possible to use xml models with namespaces in it?

### ISSUE THREAD

**Issue by peetkes** [marklogic-community/ml-app-deployer#179]
Will it be possible to create an entity services model in XML which uses namespaces?
We are trying to setup a whole range of models in xml format and we want to use namespaces in the resulting harmonized model.

**Comment by rjrudin** [comment]
I just looked over the code in ml-javaclient-util and ml-app-deployer, and I don't see anything preventing the code generation from working with XML. Have you tried it and gotten an error?

**Comment by rjrudin** [comment]
If you do get an error with XML models, please post it as a new ticket.
