### ISSUE TITLE
DefaultAppConfigFactory.java missing support for triggers database name property

### ISSUE THREAD

**Issue by sparnell** [marklogic-community/ml-app-deployer#198]
I need to set the name of the triggers database, ideally as mlTriggersDatabaseName in gradle.properties, but I can't find any support for a triggers name property.

**Comment by rjrudin** [comment]
Ack, I'll add this to 3.1.0.

In the meantime, you can do this in build.gradle (the property is in effect syntactic sugar over this code):

    ext {
      mlAppConfig.triggersDatabaseName = "my-custom-name"
    }
