### ISSUE TITLE
mlSimpleSsl and mlAppServicesSimpleSsl act differently than mlManageSimpleSsl

### ISSUE THREAD

**Issue by rjkennedy98** [marklogic-community/ml-app-deployer#199]
I would expect mlSimpleSsl and mlAppServicesSimpleSsl  to function as booleans.

Instead there is just a null check:

[link for mlSimpleSsl](https://github.com/marklogic-community/ml-app-deployer/blob/b15b751d4acf19736a6f317c5ab9db888d107262/src/main/java/com/marklogic/appdeployer/DefaultAppConfigFactory.java#L322)
```java
		if (getProperty("mlSimpleSsl") != null) {
			logger.info(
				"Using simple SSL context and 'ANY' hostname verifier for authenticating against client REST API server");
			c.setSimpleSslConfig();
		}
```

[link for mlAppServicesSimpleSsl](https://github.com/marklogic-community/ml-app-deployer/blob/b15b751d4acf19736a6f317c5ab9db888d107262/src/main/java/com/marklogic/appdeployer/DefaultAppConfigFactory.java#L220)
```java
		if (getProperty("mlAppServicesSimpleSsl") != null) {
			logger.info("Using simple SSL context and 'ANY' hostname verifier for authenticating against the App-Services server");
			c.setAppServicesSimpleSslConfig();
		}
```

mlManageSimpleSsl works as a boolean which is the expected behavior:

[link for mlManageSimpleSsl](https://github.com/marklogic-community/ml-app-deployer/blob/b15b751d4acf19736a6f317c5ab9db888d107262/src/main/java/com/marklogic/mgmt/DefaultManageConfigFactory.java#L63)
```java
	    prop = getProperty("mlManageSimpleSsl");
	    if (prop != null) {
		    logger.info("Use simple SSL for Manage app server: " + prop);
		    c.setConfigureSimpleSsl(Boolean.parseBoolean(prop));
	    }
```

**Comment by rjrudin** [comment]
Good point - I'll change it as part of 3.1.0.
