### ISSUE TITLE
Updating/Deleting servers with group name in payload

### ISSUE THREAD

**Issue by cskeefer** [marklogic-community/ml-app-deployer#201]
I'm seeing this issue from ml-gradle but think it could be addressed here. 

Using ml-gradle, I have mlGroupName set to 'e-nodes' because that is where most of the servers live. However, I need to add a few servers to the 'd-nodes' group. I can set 'group-name' accordingly in the payload and the server gets created fine. However, when it tries to update or delete the servers, it puts the 'group-id' parameter on the URL and sets  it to 'e-nodes'. This causes the put call to fail saying the group name is not consistent because it is one thing in the URL parameter, and another in the payload. The delete call doesn't report an error but again specifies the wrong group so the server doesn't get deleted.

I'm not sure how to get around this except by updating to let a group name in the payload override the configured group name. In looking into it, ServerManager overrides getResourcePath (used by delete) and getPropertiesPath (used by update) and throws the group-id URL parameter in. Doesn't seem like there is access to the payload at that point to look for a group name though. Might have to override the save/delete methods? Or perhaps I've just overlooked a configuration solution.

**Comment by rjrudin** [comment]
Is the root problem that mlGroupName, being a single property with a single value, doesn't work when you're dealing with multiple groups?

And thus the solution is that certain commands need to be smart enough to say - hey, I should see if there's a group value in the payload, and if so, I'll use that instead of appConfig.getGroupName?

**Comment by cskeefer** [comment]
Yes, that is exactly the root problem. Overriding the appConfig.getGroupName with a group-name in the payload (if present) would be ideal.
