### ISSUE TITLE
Allow me to pass in SSLContext and HostVerify to RestTemplateUtil

### ISSUE THREAD

**Issue by paxtonhare** [marklogic-community/ml-app-deployer#224]
I have my own context and verify. I'd like to be able to pass them to RestTemplateUtil.newRestTemplate.

**Comment by rjrudin** [comment]
ManageConfig now has sslContext, hostnameVerifier, adminSslContext, and adminHostnameVerifier fields. These won't have ml* properties to go with them because they're complex objects, but you can set any implementation of SSLContext/X509HostnameVerifier on them.

**Comment by rjrudin** [comment]
ManageConfig and AdminConfig now have sslContext and hostnameVerifier properties.
