### ISSUE TITLE
Databases not deployed in order when all specify schema-database

### ISSUE THREAD

**Issue by rjrudin** [marklogic-community/ml-app-deployer#225]
This applies to any "other" database file - i.e. not content-database.json, schemas-database.json, or triggers-database.json.

Example - content database:

{
	"database-name": "my-content",
	"schema-database": "my-schemas"
}

schemas database:

{
	"database-name": "my-schemas",
	"schema-database": "Schemas"
}

**Comment by kghmanuel** [comment]
Kindly add to the scenario:

{
"database-name": "my-content",
"schema-database": "my-schemas",
"triggers-database": "my-triggers"
}

**Comment by rjrudin** [comment]
Opened up PR - https://github.com/marklogic-community/ml-app-deployer/pull/229
