### ISSUE TITLE
Implement SecurityManager for exporting/importing wallet and rotating encryption keys

### ISSUE THREAD

**Issue by davidbcollins** [marklogic-community/ml-app-deployer#231]
Implement a SecurityManager that interfaces with the following:
http://docs.marklogic.com/REST/POST/manage/v2/security

This issue is a dependency of the following issue in ml-gradle:
https://github.com/marklogic-community/ml-gradle/issues/290

**Comment by davidbcollins** [comment]
@rjrudin I have started implementing this

**Comment by rjrudin** [comment]
@davidbcollins I'd like to get this into a release soon; do you have a schedule in mind for it? No problem if you want to drop it and pick up something else.

**Comment by rjrudin** [comment]
I'm putting together a basic implementation of this to cover the 5 operations. The tests are minimal for now, as I don't have a good solution for testing the import and export of a wallet (don't know how to delete a wallet).

**Comment by rjrudin** [comment]
Decided not to include support for this because the API is so simple
