### ISSUE TITLE
Prototype using OkHttp with RestTemplate

### ISSUE THREAD

**Issue by rjrudin** [marklogic-community/ml-app-deployer#250]
The goal is to minimize the number of dependencies for ml-app-deployer

**Comment by dmcassel** [comment]
Breaking change when using SSL

**Comment by popzip** [comment]
Replace library, make it work, upgrade path. Deprecation warning?

**Comment by rjrudin** [comment]
I'm closing this, given that DHF is currently using RestTemplate with HttpClient to avoid some streaming limitations with OkHttp. So there just isn't any motivation for this.
