### ISSUE TITLE
ELS endpoints require security user connection

### ISSUE THREAD

**Issue by grechaw** [marklogic-community/ml-app-deployer#258]
I discovered while developing DHF deployments that there is a small bug in 

ProtectedPathManager
QueryRolesetsManager

The unit tests were actually failing on a recent b9 build, so perhaps the bug is not exposed in current releases.  In any event, I've got a patch, and soon a PR, that fixes the issue by overriding useSecurityConfig() in each of these two classes.  I think that's the right thing to do, and the tests now pass.

**Comment by rjrudin** [comment]
Thanks @grechaw - how urgent is a fix for this? I can make an ml-app-deployer and ml-gradle 3.6.2 right now.

**Comment by grechaw** [comment]
A release would enable me to finish a sprint on time and finish a demo for MarkLogic World.  Doing it now would exceed my wildest expectations.

**Comment by rjrudin** [comment]
If I only publish 3.6.2 of ml-app-deployer, is that okay? You can force ml-gradle to use a different version of ml-app-deployer
