### ISSUE TITLE
ADMIN-DATABASEINUSE when trying to undeploy (undo)

### ISSUE THREAD

**Issue by xquery** [marklogic-community/ml-app-deployer#260]
[app-deploy-bug.zip](https://github.com/marklogic-community/ml-app-deployer/files/1843231/app-deploy-bug.zip)

(raising this as app-deployer bug, though was easier to demonstrate using ml-gradle - I hope that is ok)

installing with this configuration runs fine:

`gradle install`

though I see some complaint about 'unable to map database payload to Database object'.

```
:mlDeployCustomForests
:mlDeleteModuleTimestampsFile
:mlPrepareRestApiDependencies
:mlDeployApp
Unable to map database payload to Database object, will not be able to determine the right order in which to deploy this database; cause: Unable to read resource payload: unexpected element (uri:"http://marklogic.com/manage/database/properties", local:"database-properties"). Expected elements are (none)
Unable to map database payload to Database object, will not be able to determine the right order in which to deploy this database; cause: Unable to read resource payload: unexpected element (uri:"http://marklogic.com/manage/database/properties", local:"database-properties"). Expected elements are (none)
:mlPostDeploy UP-TO-DATE
:mlDeploy
:install
```

attempting to uninstall, running

`
gradle uninstall
`

throws an `ADMIN-DATABASEINUSE` error

```
:mlUndeployApp
Unable to map database payload to Database object, will not be able to determine the right order in which to deploy this database; cause: Unable to read resource payload: unexpected element (uri:"http://marklogic.com/manage/database/properties", local:"database-properties"). Expected elements are (none)
Unable to map database payload to Database object, will not be able to determine the right order in which to deploy this database; cause: Unable to read resource payload: unexpected element (uri:"http://marklogic.com/manage/database/properties", local:"database-properties"). Expected elements are (none)
Logging HTTP response body to assist with debugging: <error xmlns="http://marklogic.com/xdmp/error">
  <status-code>500</status-code>
  <status>Internal Server Error</status>
  <message-code>ADMIN-DATABASEINUSE</message-code>
  <message>ADMIN-DATABASEINUSE: (err:FOER0000) The following databases still refer to this database as their schema database: master.</message>
</error>

:mlUndeployApp FAILED
```

Presumably this is due to an attempt to delete the master-schemas or master-triggers database before deleting master database, as per enforced order in the ml-configs/database directory.

Could this be some issue with using xml representation of properties or an ordering issue with undeploying databases. I am not 'wed' to xml representation though it is useful for schema validation.

Note - using either 'http://marklogic.com/manage' or 'http://marklogic.com/manage/database/properties' for namespace yields the same.

Note - using ml-gradle 3.6.0 (and tested 3.4.0) on linux against linux MarkLogic cluster.

**Comment by rjrudin** [comment]
Yeah this is due to the files being XML, and the Database object hasn't been mapped via JAXB yet. Running mlUndeploy shows the following warning:

    Unable to map database payload to Database object, will not be able to determine the right order in which to deploy this database; cause: Unable to read resource payload: unexpected element (uri:"http://marklogic.com/manage/database/properties", local:"database-properties"). Expected elements are (none)

I'll take a crack at annotating the Database object so that XML is supposed.
