### ISSUE TITLE
Create roles via CMA

### ISSUE THREAD

**Issue by rjrudin** [marklogic-community/ml-app-deployer#277]

**Comment by rjrudin** [comment]
@xquery I haven't had luck with this yet. I have a test with 4 roles with dependencies across them, where ml-app-deployer today deploys them twice - one without role dependencies, the second time with them, thus ensuring that any dependent roles exist first. 

But I can't get this to work with CMA. If I make one call to /manage/v3 with all 4 roles, the call fails because the roles aren't being created in the correct order. 

I then tried two calls to /manage/v3, the first time with no role dependencies (which succeeds), the second time with role dependencies - but that fails with the following error:

    {"errorResponse":{"statusCode":"500", "status":"Internal Server Error", "messageCode":"CMA-ERRORCONFIG", "message":"CMA-ERRORCONFIG (err:FOER0000): MANAGE-CONFLICTINGCONFIGerr:FOER00001.0-mlA conflict has been detected: MANAGE-CONFLICTINGCONFIG: (err:FOER0000) A conflict has been detected:  roles differ.false roles differ./MarkLogic/manage/models/security-model.xqy36066umod:check-same-strings(xs:NMTOKEN(\"app-user\"), (), \"roles\")str1xs:NMTOKEN(\"app-user\")str2()desc\"roles\"diff1xs:NMTOKEN(\"app-user\")diff2()1.0-ml/MarkLogic/manage/models/security-model.xqy35704umod:check-same-roles(xs:NMTOKEN(\"app-user\"), ())namesxs:NMTOKEN(\"app-user\")roles()rnames()1

Any thoughts on how to get around this, or is it not yet possible in 9.0-5?

**Comment by rjrudin** [comment]
Just tested the 277-roles branch on ML 9.0-7.2 - multiple tests in DeployRolesWithDependenciesTest are still failing.

**Comment by rjrudin** [comment]
Verified there are still issues here when doing a single CMA call - the roles have to be ordered in the config correctly. For example, for this payload:

```
{
  "config" : [ {
    "role" : [ {
      "role-name" : "xyz-admin",
      "role" : [ "xyz-reader", "xyz-writer" ]
    }, {
      "role-name" : "xyz-reader"
    }, {
      "role-name" : "xyz-writer",
      "role" : [ "xyz-reader", "app-user" ]
    } ]
  } ]
}
```

All 3 roles will be created, but xyz-admin won't have any inherited roles because they're defined later in the array. But xyz-writer will have xyz-reader since it's defined before xyz-writer.

**Comment by xquery** [comment]
have you tried reordering the array to create xyz-reader and xyz-writer first ?  in any event CMA does not guarantee solving existing dependencies built into the server ... you may have to perform 2 independent calls for this to work. That being said, I may take a look at this specific use case and 'just make it work'... will depend on time/priority.

**Comment by rjrudin** [comment]
@xquery I had tried to write an ordering function for roles before, but could never get it working completely, and then adopted a recommendation to make two calls for roles - one without any role dependencies (so all roles are created first), and then a second with role dependencies. That has worked well for granular calls.

I tried the same thing with CMA, such that the first call has this payload:

```
{
  "config" : [ {
    "role" : [ {
      "role-name" : "xyz-admin"
    }, {
      "role-name" : "xyz-reader"
    }, {
      "role-name" : "xyz-writer"
    } ]
  } ]
}
```

And then the second call has this payload (xyz-reader isn't included in the second call because it doesn't have any role dependencies):

```
{
  "config" : [ {
    "role" : [ {
      "role-name" : "xyz-admin",
      "role" : [ "xyz-reader", "xyz-writer" ]
    }, {
      "role-name" : "xyz-writer",
      "role" : [ "xyz-reader", "app-user" ]
    } ]
  } ]
}
```

But that doesn't update either xyz-admin or xyz-writer - the "role" array is seemingly ignored for both roles. Seem like a bug worth filing?

I'm going to hold off on including CMA support for roles in 3.11.0 ml-app-deployer - I'm adding privileges, which seems to work well (though not documented).

**Comment by rjrudin** [comment]
Seems to be working now on 9.0-9 when submitting two separate config objects in the same CMA request.

**Comment by xquery** [comment]
good to hear things are working

J

**Comment by dixitsingla** [comment]
After upgrading the ml-gradle to **v3.16.4** I am still facing the same issue.

I have checked the configuration passed and it looks the roles config are in the right order.

Note: On running the **mlDeploySecurity** task first time I don't see any error, on running the same second time getting the error.
