### ISSUE TITLE
Manage temporal config via Mgmt API

### ISSUE THREAD

**Issue by rjrudin** [marklogic-community/ml-app-deployer#28]
As an ML developer
I want to TITLE
So that I don't have to manually configure bitemporal features in an application
- I think an AxesManager that extends AbstractResourceManager would work for the /axes endpoints, as those URL patterns fit the assumptions that AbstractResourceManager makes.
- I don't think a CollectionsManager can extend AbstractResourceManager, because the URL pattern - which requires a collection param on the querystring - fits the assumptions made by AbstractResourceManager. 
- Looks like the LSQT stuff needs separate public methods as well

**Comment by tcfenstermaker** [comment]
Steps for creating a temporal (aka bitemporal) database in ML8 (assumes `temporal = require("/MarkLogic/temporal.xqy");`)
1. Use `admin.databaseAddRangeElementIndex` to create four index, one each for start and end times for both the valid and system times.
2. Use `temporal.axisCreate` to create the valid and system axes bound to the range indexes.
3. Use `temporal.collectionCreate` to create a temporal collection which uses the two axes.

**Comment by rjrudin** [comment]
Trebor - note that you can create the range index via the ml-config/databases/content-database.json file. And I'm assuming the temporal management endpoints provide a way to do the "axisCreate" and "collectionCreate" stuff - e.g. https://docs.marklogic.com/REST/POST/manage/v2/databases/[id-or-name]/temporal/axes

Basically, there shouldn't be any need to write any ML code - should just be able to read JSON/XML files from disk that define the axis/collection, and then call the appropriate endpoint.

**Comment by tcfenstermaker** [comment]
Current approach:
- Create new packages `com.marklogic.rest.mgmt.temporal` and `com.marklogic.appdeployer.command.temporal`
- Create new classes `com.marklogic.rest.mgmt.temporal.AxesManager` and `com.marklogic.appdeployer.command.temporal.CreateAxesCommand` (these classes most likely will extend `AbstractResourceManager` and `AbstractResourceCommand` respectively)
- Add an item in `com.marklogic.appdeployer.command.SortOrderConstants` to give an order for the creation of axes relative to other app creation tasks

**Comment by rjrudin** [comment]
Addressed in other ticket / pull request
