### ISSUE TITLE
Support invoking certificate template operations via files

### ISSUE THREAD

**Issue by rjrudin** [marklogic-community/ml-app-deployer#280]
http://docs.marklogic.com/REST/POST/manage/v2/certificate-templates/[id-or-name]

**Comment by stevenbrockman** [comment]
Rob - FYI- my pull request only adds support for inserting host certificates. 

Perhaps you may want to add a new issue for that?  And leave this ticket open in the future, the issue with those other commands within that API, the others mainly request information about the templates, and does not really help ml-app-deployer create ML configs.

**Comment by rjrudin** [comment]
Calling this done as a result of pull request #282
