### ISSUE TITLE
ManageConfig requires additional setSecuritySslContext() method

### ISSUE THREAD

**Issue by srinathgit** [marklogic-community/ml-app-deployer#295]
1. ManageConfig has two set of credentials; username/password and securityUsername/securityPassword to be used in different circumstances. But there is only on sslContext. 
2. In scenarios where server is set to certificate based authentication, 'sslContext' has to be set to the one generated with a user whose role is a union of  'username' and 'securityUsername' users, else some requests would fail

**Comment by rjrudin** [comment]
What do you propose as a solution for this? A separate e.g. "securitySslContext" field that would be used by ManageClient instead of config.getSslContext? 

Should this also be done for hostnameVerifier - i.e. add securityHostnameVerifier?

**Comment by srinathgit** [comment]
1.  Yes , a  "securitySslContext" field that would be used by ManageClient instead of config.getSslContext is required. Regarding 'securityHostnameVerifier', I had a conversation with @vivekmuniyandi  and we think we don't need an additional hostname verifier for 'securityUsername' , the one we already have should suffice.
2. Additionally, in ManageClient.setManageConfig(ManageConfig config), while creating 'securityUserRestTemplate' , the  "securitySslContext" should be used
