### ISSUE TITLE
ml-gradle checks for RestAPI server on Default group even if server is targeted on another group.

### ISSUE THREAD

**Issue by gku11ava** [marklogic-community/ml-app-deployer#298]
RestApiManager.java checks for the RestAPI server on the Default group because it instantiates a default ServerManager without providing a group name.

Proposed Fix:
com.marklogic.mgmt.api.restapi RestApi.java should pass it's group variable as an argument when it instantiates an instance of the RestApiManager.

RestApiManager should have a private String variable for storing group name and include a constructor that accepts a group name argument.  If no group name is provided, it remains null.  When ServerManager gets created as part of the call to restApiServerExists, if group != null, the group name should be passed as an argument with the ServerManager constructor.

**Comment by rjrudin** [comment]
Thanks @gku11ava - how soon do you need a fix? I can toss out a 3.8.4 fairly quickly, just wondering if I should wait for any other issues to pop up, or if you'd like this ASAP (ASAP is totally fine).

**Comment by gku11ava** [comment]
@rjrudin It's not a major priority as we can workaround it by having a default group configured (even if it is empty).   There doesn't seem to be a problem in subsequent deployments where the Rest API server already exists.
