### ISSUE TITLE
If DatabaseManager.clearDatabase command fails, try again with forest clear

### ISSUE THREAD

**Issue by derms** [marklogic-community/ml-app-deployer#300]
With the advent of granular privileges, it is possible to assign granular forest management to a specific database -

   http://marklogic.com/xdmp/privileges/admin/database/forests/{database-id}

This allows a user with this privilege to clear the db.

So if the initial database clear operation fails, retry with the following server-side eval

`
xdmp.forestClear(xdmp.databaseForests(xdmp.database('databaseName')))
`

Related to 
https://github.com/marklogic-community/ml-gradle/issues/378

**Comment by rjrudin** [comment]
What's the use case for a user who can clear all the forests for a database, but not actually clear the database?

**Comment by derms** [comment]
since 9.0-7, this is no longer needed as granular privileges work now with the REST-API
