### ISSUE TITLE
Support for environment-based config

### ISSUE THREAD

**Issue by cskeefer** [marklogic-community/ml-app-deployer#301]
The data-explorer project uses the ml-app-deployer deployer library in the form of an executable JAR to deploy the application. The project includes a role that now contains a few ML9-only execute privileges which prevents the deploy from working with ML8. In the case of deploying to ML8, it would be nice to have a way to specify a specific version of the role file that doesn't have the offending privileges. More generally, it would be nice to specify more than one config path based on a environmental situation.  

Pinging @rjrudin with this as requested

**Comment by rjrudin** [comment]
@cskeefer Can you actually create this ticket in the data-explorer project? I am fairly certain the change will be in that project, not in ml-app-deployer.

**Comment by cskeefer** [comment]
ha, @rjrudin you mean actually create it where you asked for it to be created? I'll see what I can do.
