### ISSUE TITLE
Manage super and sub databases via Mgmt API

### ISSUE THREAD

**Issue by rjrudin** [marklogic-community/ml-app-deployer#31]

**Comment by rjrudin** [comment]
This may not be necessary - the databases endpoint already allows for subdatabases to be configured on a database.

**Comment by cskeefer** [comment]
I was just looking at the 9.0 REST API docs. 8.0 had a dedicated section called Super-databases and Sub-databases under the Management API section. 9.0 does not have that.

**Comment by cskeefer** [comment]
Seems like in 8.0 you could both:
* Create a sub-database based on an existing database: POST to /manage/v2/databases/{id|name}/sub-databases
* Create a super-database based on an existing database: POST /manage/v2/databases/{id|name}/super-databases

The 9.0 docs leave out the those endpoints but I did just try creating a sub-database using it (on a 9.0-1.1 instance) and it created the sub-database just fine (including range index settings, etc). I wonder if it is a doc oversight.

I haven't tried creating a sub-database using /manage/v2/databases/{id|name}/properties (I'm assuming that is what you are talking about) but the docs don't look like you can specify the same parameters. They seem to say you specify database-name and cluster-name where as the docs for the /manage/v2/databases/{id|name}/sub-databases endpoint say to specify database-name and kind (active or archive)
