### ISSUE TITLE
Distribute replica forests evenly

### ISSUE THREAD

**Issue by dmcassel** [marklogic-community/ml-app-deployer#330]
Given some number of forests per host and a number of replicas (in my case, 1), ml-gradle currently puts each forest's replica on the next host -- so all of host1's forests are replicated on host2, all of host2's forests are replicated on host3, etc. Erin Miller's [Hardware Reference Architecture: Direct Attached Storage](https://developer.marklogic.com/media/white-paper/hardware-reference-arch-das.pdf) recommends not doing this: "Assuming 6 primary and 6 replica forests per host, it’s important to distribute forests equally across hosts. Specifically, you don’t want to replicate all forests from host 1 to host 2. If host 1 then goes down, host 2 will be supporting 12 primary forests, since the six replicas will have changed roles to primary. "

Modify the replica host assignment such that replicas for a host's forests are evenly distributed around the cluster.

**Comment by rjrudin** [comment]
I added this commit after merging in the PR: 

https://github.com/marklogic-community/ml-app-deployer/commit/d54677533df6ca144e91a2ef9dfaf0c812a0d8a2

BuildForestTest is passing, and I used ConfigureReplicaForestsDebug on a local 3-host cluster to try out both strategies, and all appears well. 

I may do a 3.12.beta release of ml-gradle though so you can try this out ASAP.

**Comment by rjrudin** [comment]
Added docs at https://github.com/marklogic-community/ml-gradle/wiki/Creating-forests#replica-forest-creation . This is in case we run into any issues with the Distributed implementation in the 3.12.0 release.
