### ISSUE TITLE
mlLoadData not working for certain binaries

### ISSUE THREAD

**Issue by derms** [marklogic-community/ml-app-deployer#358]
When you use the mlLoadData command to load pdf and docx binaries, the are not loaded correctly (the pdf becomes blank and the docx file becomes corrupted).

If I do one (or both) of the following, it works - 

in **gradle.properties**
`mlDataReplaceTokens=false
`

or in **build.gradle**
`mlAppConfig.additionalBinaryExtensions = [".pdf",".docx"]
`

it seems as though the mlLoadData command is not treating the ".pdf",".docx" as binaries when trying to replace tokens in the files.

**Comment by rjrudin** [comment]
Closing this in favor of https://github.com/marklogic-community/ml-javaclient-util/issues/114
