### ISSUE TITLE
Setting mlSimpleSsl or mlAppServicesSimpleSsl to true not working with jdk versions > 8

### ISSUE THREAD

**Issue by srinathgit** [marklogic-community/ml-app-deployer#361]
With mlSimpleSsl or mlAppServicesSimpleSsl set to true, we are hitting the issue documented in https://github.com/marklogic/java-client-api/issues/1033. In 4.2.0,  for jdk versions > 9, java client api sets the default trust manager if not set. This will not work since with simplessl since we don't add the root ca to the default trust store. So, application has to set the trustmanager explicitly, something like appConfig.setAppServicesTrustManager(new SimpleX509TrustManager());  and appConfig.setAppServicesTrustManager(new SimpleX509TrustManager()) in AppConfig.setSimpleSslConfig() and AppConfig.setAppServicesSimpleSslConfig() methods

**Comment by aebadirad** [comment]
@rjrudin this on your radar?

**Comment by rjrudin** [comment]
I'll take a look at it.

**Comment by rjrudin** [comment]
Just did a quick verification - using the example ssl-project in ml-gradle, deployment succeeded on Java 8 and failed on Java 11. Looking into a fix.

**Comment by rjrudin** [comment]
Thanks @srinathgit this was as simple as you suggested - just setting a SimpleX509TrustManager by default.
