### ISSUE TITLE
Database sorting not working when multiple files have schema and security databases set

### ISSUE THREAD

**Issue by rjrudin** [marklogic-community/ml-app-deployer#368]
This was captured from https://github.com/marklogic-community/ml-gradle/issues/488 

The following set of databases will cause the problem:

```
"database" : [ {
      "database-name" : "test-content",
      "security-database" : "Security",
      "schema-database" : "Schemas",
      "triggers-database" : "test-triggers"
    }, {
      "database-name" : "test-content-test",
      "security-database" : "Security",
      "schema-database" : "Schemas",
      "triggers-database" : "test-triggers"
    }, {
      "database-name" : "test-modules",
      "security-database" : "Security",
      "schema-database" : "Schemas",
      "enabled" : true
    }, {
      "database-name" : "test-triggers",
      "security-database" : "Security",
      "schema-database" : "Schemas"
    } ]
```

Should be able to adopt the sorting strategy used for roles in order to fix this.

**Comment by grtjn** [comment]
@rjrudin have you ever considered deploying this in 2 passes? create all dbs without links first, and add links in between afterwards? You could also argue that Manage rest api should be smart enough to figure this out though..

**Comment by rjrudin** [comment]
Roles had previously been done in two passes, but then I found this topological sort routine - http://www.java2s.com/Code/Java/Collections-Data-Structure/Topologicalsorting.htm - that was perfect for sorting things with dependencies.

**Comment by grtjn** [comment]
Yeah, sounds interesting, but sorting alone would not work with cyclic dependencies. That can happen when one inherits another role, but the other has default permissions for itself and the first.

Speaking of dbs, can you create a db using itself as schemas db? Wondering about it since sorting would not fix this, unless it just works..
