### ISSUE TITLE
Allow multiple tasks that only differ by `task-root` to be imported.

### ISSUE THREAD

**Issue by ahwitz** [marklogic-community/ml-app-deployer#406]
We have a case where two `filesystem` AppServers are served using almost-identical codebases which include scheduled tasks. This means that we have two scheduled tasks that need to be deployed with identical configuration except for the `task-root` property. Running `gradle -i mlDeployTasks` with configurations for both of these tasks causes only the second one encountered to be stored.

Full report/test cases in https://github.com/marklogic-community/ml-gradle/issues/547.

We'll look into upgrading to JDK 9+ to support an `ml-gradle` 4.x requirement, but if it's straightforward for this to be (also?) released as a 3.x.x minor version, that'd be more than welcome.

**Comment by ahwitz** [comment]
As an update: we've upgraded to dual JDK8/11 with `ml-gradle` pointing to JDK11 without an issue. We can set up an ml-gradle 4.x version without an issue.

**Comment by rjrudin** [comment]
Confirming - addressing this in a 4.0.x or 4.1.0 release works for you then?

**Comment by ahwitz** [comment]
Yup. Shouldn't be an issue at all.

**Comment by rjrudin** [comment]
See the commit linked to this - the tests indicate this does the trick. I noticed that task-type would be easy to add for matching as well too.
