### ISSUE TITLE
LoadSchemasCommand shouldn't throw an error for empty directory

### ISSUE THREAD

**Issue by rjrudin** [marklogic-community/ml-app-deployer#414]
If the empty directory has a name that doesn't correspond to a database, that's fine, no need for an error or likely even a log message.

**Comment by damonfeldman** [comment]
Note that the symptom of this issue will be a gradle failure message like:
```

What went wrong:
Execution failed for task ':mlDeployApp'.
> Could not determine database to associate with database resource directory: /Users/Someusername/workspaces/projectname/src/main/ml-config/databases/data-hub-staging-SCHEMAS

```
This can particularly happen if you run an mlDeploy or mlDeployApp using older or default database names, which creates the directories, then you change those names and redeploy. The config files appear to be removed, but the enclosing directory remains, which is currently an issue for gradle.

It may be worth logging that there is an obsolete config directory out of sync with the properties defined in gradle.properties, particularly if there are config files in there which are going to be ignored.
