### ISSUE TITLE
insert-host-certificates fails in cluster scenario

### ISSUE THREAD

**Issue by stevenbrockman** [marklogic-community/ml-app-deployer#419]
When there are multiple nodes in a cluster.. ml-app-deployer fails to insert more than one certificate found under the host-certificates/TEMPLATENAME directory.

InsertCertificateHostsTemplateCommand should check for existence of the certificate in the template based on hostname, to see if the certificate exists specific to the host key pair found.

**Comment by rjrudin** [comment]
@stevenbrockman See https://github.com/marklogic-community/ml-app-deployer/commit/476a579db3c3a1c42d76fff634f8874fa665c643 - this is now using the /v1/eval endpoint in the Manage server to extract the host name from the public cert file, as you suggested.

**Comment by rjrudin** [comment]
I'm doing a 4.1.1 release soon, so try testing that - if anything pops up, open a new ticket.
