### ISSUE TITLE
ManageClient putJson method returning 405 on PUT to /manage/v2/credentials

### ISSUE THREAD

**Issue by gku11ava** [marklogic-community/ml-app-deployer#430]
Defined a custom task in ml-gradle to set AWS access & secret keys using ManageClient and putJson method.

getManageClient().putJson("/manage/v2/credentials", '{"type":"aws", "access-key":"key", "secret-key":"key"}')

This output is returned:
Logging HTTP response body to assist with debugging: {"errorResponse":{"statusCode":"405", "status":"Method not allowed", "messageCode":"REST-UNSUPPORTEDMETHOD", "message":"REST-UNSUPPORTEDMETHOD: (err:FOER0000) Endpoint does not support method: Set aws credentials by applying PUT to manage/v2/credentials/properties."}}

This occurs in both MarkLogic 9.0.12 and 10.0.3.  The same payload sent via curl works.

**Comment by rjrudin** [comment]
I believe the error message is telling you what to do - you need to send the request to /manage/v2/credentials/properties, not /manage/v2/credentials.

See https://docs.marklogic.com/REST/PUT/manage/v2/credentials/properties
