### ISSUE TITLE
Make replicas work with mlDatabasesWithForestsOnOneHost

### ISSUE THREAD

**Issue by dmcassel** [marklogic-community/ml-app-deployer#431]
For modules, schemas, and triggers databases, it makes sense to deploy a forest to just one host in a cluster. We can do this with the `mlDatabasesWithForestsOnOneHost` property. However, I also want to set up replicas for those forests. It looks like that's not supported. 

Example gradle properties:
```
# gradle-prod.properties
mlDatabasesWithForestsOnOneHost=myApp-modules,myApp-schemas,myApp-triggers
mlDatabaseNamesAndReplicaCounts=myApp-content,1,myApp-modules,1,myApp-schemas,1,myApp-triggers,1
```

The mlPrintForestPlan command shows an error with the configuration above. 

```
./gradlew mlPrintForestPlan -Pdatabase=myApp-modules -PenvironmentName=prod
> Task :mlPrintForestPlan FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mlPrintForestPlan'.
> Not enough hosts exists to create 1 replicas for database 'myApp-modules'; possible hosts, which may include the host with the primary forest and thus cannot have a replica: [myHost1]

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 4s
1 actionable task: 1 executed
```

Versions:

- MarkLogic: 10.0-5.1
- ml-gradle: 6.3
- JDK: openjdk version "13.0.2" 2020-01-14

**Comment by rjrudin** [comment]
Does deploying the databases work? Wondering if it's just a bug in the code for determining the forest plan.

**Comment by dmcassel** [comment]
I encountered this while adjusting properties for a production environment, so I didn't try. I'll have to set up a safe test.

**Comment by rjrudin** [comment]
Figured the root cause is that HostCalculator returns a list of one host name when a database should only have forests on one host. But that list is used for replicas as well, which leads to the error. HostCalculator needs to return two lists - one for primary forest hosts, and one for replica forest hosts.
