### ISSUE TITLE
Add prefix in URI while loading XQuery file using ml-gradle

### ISSUE THREAD

**Issue by dharmendra1985** [marklogic-community/ml-app-deployer#436]
Hi All,

I am using gradle 6.8 and MarkLogic version is 10.0-5.2,

My XQuery code is in directory \ml-gradle\src\main\common. When I run the command mlLoadModules to load XQuery into the modules database it loads with default URI /common/test.xqy.

I want to add some prefix to the URIs e.g. /rsc/common/test.xqy. 

Note: I don't want to create an extra folder in my source for prefix "rsc".

As i have two different module database where the common xquery files can be loaded from common directory, so if create a rsc directory then the prefix "rsc" will appear in both URI .As I want that for the one module database URI will be different.

I had added this issue on stackoverflow earlier you can find more details on below given link: 

[https://stackoverflow.com/questions/66517081/how-to-add-prefix-in-uri-while-loading-xquery-file-using-ml-gradle/66530641?noredirect=1#comment117643647_66530641](url)

**Comment by rjrudin** [comment]
New property will be "mlModuleUriPrefix"
